### PR TITLE
Add SQS events support

### PR DESCRIPTION
**Pull request by barryib**
### Description of changes:
This will add SQS support. With SQS we can run lambda with a custom batch size (1 per exemple). This is very useful when you are using terraform instead of cloudformation for EKS upgrade.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by svozza** [comment]
Can you explain the use case to me a bit better as I've never used Terraform? The issue I see here is that there is now a mismatch between the CloudFormation and lambda. If we decide to proceed with this, the CloudFormation should take the SQS as a parameter and attach the lambda to it with a configurable batch size. I worry that this change might make this project try to do too much.

**Comment by barryib** [comment]
> Can you explain the use case to me a bit better (as I've never used Terraform)?

@svozza When you are using cloudformation, you can upgrade your cluster node by node with the `AutoScalingRollingUpdate` update policy. This will let your lambda function drain nodes one by one.

But in Terraform, you can't control the update policy (because, AWS doesn't expose it in the autoscaling group api. See https://github.com/hashicorp/terraform/issues/1552 for more info). So, when you are doing some kind of blue/green deployment with Terraform, you have to drain node in batch (one by one per exemple) to avoid outage.

The only way, I see to manage this is to send autoscaling group lifecycle hooks notifications into a SQS queue and let lambda consume them one by one.

> The issue I see here is that there is now a mismatch between the CloudFormation and lambda.

There is no change. The lambda works as before. I just added an env var `USE_SQS_EVENTS` to run the lambda in "SQS mode". Lifecycle hooks events are same in both case.

**Comment by svozza** [comment]
Ah OK, that makes sense. I'd forgotten you can send lifecycle events to SQS, the issue still remains though, I need to change the CloudFormation here because this solution has to work for everyone. LEave it with me but also, you'll need to add a test for the new code path, it should be pretty much identical to the ones there all you do is add an extra environment variable and test event.

**Comment by barryib** [comment]
> you'll need to add a test for the new code path, it should be pretty much identical to the ones there all you do is add an extra environment variable and test event.

Sure !

**Comment by RyPeck** [comment]
Has this gone anywhere? Looks to have stalled out here on the PR.

**Comment by ctd** [comment]
I'm closing this request due to inactivity. Please reopen the request if you think it's still relevant and are willing to make the requested changes for it to be merged.

**Pull request closed without merging**
